// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { CeloDuels$Type } from "./CeloDuels";
import { IERC20$Type } from "./IERC20";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CeloDuels"]: CeloDuels$Type;
    ["IERC20"]: IERC20$Type;
    ["contracts/CeloDuels.sol:CeloDuels"]: CeloDuels$Type;
    ["contracts/CeloDuels.sol:IERC20"]: IERC20$Type;
  }

  interface ContractTypesMap {
    ["CeloDuels"]: GetContractReturnType<CeloDuels$Type["abi"]>;
    ["IERC20"]: GetContractReturnType<IERC20$Type["abi"]>;
    ["contracts/CeloDuels.sol:CeloDuels"]: GetContractReturnType<CeloDuels$Type["abi"]>;
    ["contracts/CeloDuels.sol:IERC20"]: GetContractReturnType<IERC20$Type["abi"]>;
  }
}
