// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { CeloDuelsMulti$Type } from "./CeloDuelsMulti";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CeloDuelsMulti"]: CeloDuelsMulti$Type;
    ["contracts/CeloDuels.sol:CeloDuelsMulti"]: CeloDuelsMulti$Type;
  }

  interface ContractTypesMap {
    ["CeloDuelsMulti"]: GetContractReturnType<CeloDuelsMulti$Type["abi"]>;
    ["contracts/CeloDuels.sol:CeloDuelsMulti"]: GetContractReturnType<CeloDuelsMulti$Type["abi"]>;
  }
}
